set-option -g default-command "arch -arch arm64 /bin/zsh"
# allows tmux to have colours
set -g default-terminal "screen-256color"
set -g mouse on
# Undercurl
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0


set-option -g status-position top
set-option -g automatic-rename on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# sets prefix to crtl + a 
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# keybinds for splitting windows
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}" -l '20%'

# allows r to reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# allows of resizing of panes by using vim movement motion
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator' # for navigating panes and vim/nvim with Ctrl-hjkl
set -g @plugin 'tmux-plugins/tmux-yank'
set -g status-interval 8

# Message style.
set -g message-style "fg=yellow,bg=default"
set -g message-command-style "fg=yellow,bg=default"

# Pane style.

# Status style.
set-option -g status-style bg=default
set -g status-left "#[fg=cyan,bg=default]#[fg=black,bg=cyan] #{session_windows}#[fg=cyan,bg=default] ⠀"
set -g status-right "#[fg=colour8,bg=default] #S #[fg=cyan,bg=default]#[fg=black,bg=cyan]󱫋 #{session_attached}#[fg=cyan,bg=default]"
set -g status-left-length 100
set -g status-position top
set -g status-justify left


# Window style.
set -g window-status-style "fg=colour8,bg=default"
set -g window-status-format "#[fg=default,bg=default] #[fg=default,bg=default]#W"
set -g window-status-separator "  "
set -g window-status-current-format "#[fg=cyan,bg=default] #[fg=cyan,bg=default]#W"
run '~/.tmux/plugins/tpm/tpm'

